"""Render the declared IAM control flow into infra/control-flow.md.

Answers three questions the manifests hold but do not present:

  1. At each step of the lifecycle, which authorization decision happens?
  2. Which of those decisions leave an audit record, and which are invisible?
  3. For a given principal, what is the complete set of actions it needs?

(3) is the one you write IAM from: it is the union of every action declared
against that principal, so anything granted beyond it is over-permission.

    python scripts/control-flow.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "infra" / "control-flow.md"
PHASES = ["build", "provision", "invoke", "teardown"]
PHASE_TITLE = {
    "build": "Build — produce the image",
    "provision": "Provision — create or update the runtime",
    "invoke": "Invoke — serve one request",
    "teardown": "Teardown",
}


def _as_list(v) -> list[str]:
    if v is None:
        return []
    return v if isinstance(v, list) else [v]


def main() -> int:
    agents: dict[str, dict] = {}
    for p in sorted((ROOT / "agents").glob("*/agent.yaml")):
        doc = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        agents[doc["metadata"]["name"]] = doc

    by_principal: dict[str, dict[str, set[str]]] = {}
    unaudited: list[tuple[str, str, str]] = []
    lines: list[str] = [
        "# IAM control flow",
        "",
        "GENERATED by `scripts/control-flow.py` from `agents/*/agent.yaml`."
        " Do not hand-edit.",
        "",
        "Every row is one authorization decision. Read top to bottom: that is the",
        "order they are evaluated in.",
        "",
    ]

    for phase in PHASES:
        lines += [f"## {PHASE_TITLE[phase]}", ""]
        lines += ["| Step | Agent | Principal | Actions | Resource | Audit |",
                  "|---|---|---|---|---|---|"]
        rows = []
        for name, doc in agents.items():
            for entry in ((doc.get("spec", {}).get("controls") or {}).get(phase) or []):
                principals = _as_list(entry.get("principal"))
                actions = entry.get("actions") or []
                res = ", ".join(_as_list(entry.get("resource"))) or "—"
                audit = entry.get("audit", "—")
                rows.append((entry["step"], name, principals, actions, res, audit))
                for pr in principals:
                    by_principal.setdefault(pr, {}).setdefault(phase, set()).update(actions)
                    for extra in entry.get("alsoRequires") or []:
                        by_principal[pr][phase].add(extra["action"])
                if audit == "none" and actions:
                    unaudited.append((entry["step"], name, ", ".join(actions)))
        for step, name, principals, actions, res, audit in sorted(rows, key=lambda r: (r[0], r[1])):
            acts = "`" + "`, `".join(actions) + "`" if actions else "*none required*"
            mark = "✅ CloudTrail" if audit == "cloudtrail" else ("⚠️ none" if audit == "none" else "—")
            lines.append(f"| {step} | {name} | {', '.join(principals)} | {acts} | `{res}` | {mark} |")
        lines.append("")

    lines += [
        "## Policy set per principal",
        "",
        "The union of every action declared against each principal — i.e. the",
        "policy that principal actually needs. Grants beyond this list are",
        "over-permission; grants missing from it will fail at the step shown above.",
        "",
    ]
    for principal in sorted(by_principal):
        allacts = sorted({a for phase in by_principal[principal].values() for a in phase})
        lines += [f"### `{principal}`", ""]
        for a in allacts:
            lines.append(f"- `{a}`")
        lines.append("")

    lines += [
        "## Steps with no audit record",
        "",
        "These authorization decisions happen but leave nothing in CloudTrail",
        "management events — data-plane calls are not recorded. They cannot be",
        "verified after the fact, which is exactly why they are declared here.",
        "",
        "| Step | Agent | Actions |",
        "|---|---|---|",
    ]
    for step, name, acts in sorted(set(unaudited)):
        lines.append(f"| {step} | {name} | `{acts}` |")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  principals: {len(by_principal)}   unaudited steps: {len(set(unaudited))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
