"""Snapshot what is actually deployed into infra/release.yaml + infra/import.yaml.

Two artifacts, two different jobs:

  release.yaml  What each runtime should serve: the image **digest** (not a tag)
                and the pinned runtime version. This is the rollback record and
                the thing Terraform needs for container_uri / target_version.

  import.yaml   Logical name -> physical resource id, so `terraform import` can
                adopt the resources that already exist instead of trying to
                create duplicates of them.

Re-run after every deploy; the diff is the release note.

    python scripts/snapshot-deployment.py [--profile agentcore-personal]
"""
from __future__ import annotations

import argparse
import datetime as _dt
from pathlib import Path

import boto3

ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = ROOT / "agents"


def _agent_names() -> list[str]:
    return sorted(p.parent.name for p in AGENTS_DIR.glob("*/agent.yaml"))


def _digest_for(ecr, repo: str, tag: str) -> str | None:
    try:
        d = ecr.describe_images(repositoryName=repo, imageIds=[{"imageTag": tag}])
        return d["imageDetails"][0]["imageDigest"]
    except Exception:  # noqa: BLE001 - a missing tag is reported, not fatal
        return None


def _yaml_dump(lines: list[str], path: Path) -> None:
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", default="agentcore-personal")
    ap.add_argument("--region", default="us-east-1")
    args = ap.parse_args()

    s = boto3.Session(profile_name=args.profile, region_name=args.region)
    ctl = s.client("bedrock-agentcore-control")
    ecr, cb, ar, sm = (s.client(x) for x in ("ecr", "codebuild", "apprunner", "secretsmanager"))
    stamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    runtimes = {r["agentRuntimeName"]: r for r in ctl.list_agent_runtimes()["agentRuntimes"]}
    memories = {m["id"].split("-")[0]: m for m in ctl.list_memories().get("memories", [])}

    rel: list[str] = [
        "# GENERATED by scripts/snapshot-deployment.py - do not hand-edit.",
        "# What each runtime is pinned to. Digests, never tags: the toolkit tags",
        "# images with a timestamp, which is not a stable identifier.",
        "apiVersion: agentcore/v1",
        "kind: Release",
        "metadata:",
        f"  capturedAt: {stamp}",
        f"  region: {args.region}",
        "spec:",
        "  agents:",
    ]
    imp: list[str] = [
        "# GENERATED by scripts/snapshot-deployment.py - do not hand-edit.",
        "# Logical name -> physical id, for one-time `terraform import` of resources",
        "# that already exist. Without this a first apply tries to create duplicates.",
        "apiVersion: agentcore/v1",
        "kind: ImportMap",
        "metadata:",
        f"  capturedAt: {stamp}",
        f"  region: {args.region}",
        "spec:",
        "  agentRuntimes:",
    ]

    for name in _agent_names():
        r = runtimes.get(name)
        if not r:
            print(f"WARN {name}: no deployed runtime found")
            continue
        full = ctl.get_agent_runtime(agentRuntimeId=r["agentRuntimeId"])
        uri = (full.get("agentRuntimeArtifact", {})
                   .get("containerConfiguration", {}).get("containerUri", ""))
        repo_part, _, tag = uri.partition(":")
        repo = repo_part.split("/")[-1]
        digest = _digest_for(ecr, repo, tag) if tag else None
        eps = ctl.list_agent_runtime_endpoints(agentRuntimeId=r["agentRuntimeId"])
        ep = (eps.get("runtimeEndpoints") or [{}])[0]

        rel += [
            f"    - name: {name}",
            f"      image:",
            f"        repository: {repo}",
            f"        digest: {digest or 'UNRESOLVED'}",
            f"        builtTag: {tag or 'none'}          # informational only",
            f"      runtimeVersion: \"{full.get('agentRuntimeVersion')}\"",
            f"      endpoint:",
            f"        name: {ep.get('name', 'DEFAULT')}",
            f"        liveVersion: \"{ep.get('liveVersion')}\"",
            f"        targetVersion: \"{ep.get('targetVersion') or full.get('agentRuntimeVersion')}\""
            "   # pin: an unset target floats",
        ]
        imp += [
            f"    - name: {name}",
            f"      runtimeId: {r['agentRuntimeId']}",
            f"      executionRole: {full.get('roleArn','').split('/')[-1]}",
            f"      ecrRepository: {repo}",
            f"      codeBuildProject: bedrock-agentcore-{name}-builder",
        ]
        mem = memories.get(f"{name}_mem")
        if mem:
            imp.append(f"      memoryId: {mem['id']}")

    # control-plane image + platform resources
    cp_repo = "agent-core-control-plane"
    svc = next((x for x in ar.list_services()["ServiceSummaryList"]
                if x["ServiceName"] == "agent-core-console"), None)
    served_tag = None
    if svc:
        d = ar.describe_service(ServiceArn=svc["ServiceArn"])["Service"]
        served_tag = (d["SourceConfiguration"]["ImageRepository"]["ImageIdentifier"]
                      .rsplit(":", 1)[-1])
    cp_digest = _digest_for(ecr, cp_repo, served_tag) if served_tag else None

    rel += [
        "  services:",
        "    - name: web-console",
        f"      image:",
        f"        repository: {cp_repo}",
        f"        tag: {served_tag or 'none'}",
        f"        digest: {cp_digest or 'UNRESOLVED'}",
    ]

    secret = next((x for x in sm.list_secrets()["SecretList"]
                   if x["Name"] == "agent-core/console-password"), None)
    imp += [
        "  platform:",
        f"    controlPlaneEcrRepository: {cp_repo}",
        f"    controlPlaneCodeBuildProject: agent-core-control-plane-builder",
        f"    appRunnerServiceId: {svc['ServiceId'] if svc else 'MISSING'}",
        f"    consolePasswordSecret: {secret['Name'] if secret else 'MISSING'}",
        "    roles:",
        "      - agent-core-cp-codebuild",
        "      - agent-core-apprunner-instance",
        "      - agent-core-apprunner-access",
    ]

    _yaml_dump(rel, ROOT / "infra" / "release.yaml")
    _yaml_dump(imp, ROOT / "infra" / "import.yaml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
